name: Node tests

on:
  push:
    branches: [master, all-eggs-in-actions]
  pull_request:
    branches: [master, all-eggs-in-actions]
  workflow_dispatch:


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        bids-examples-branch: [master]
        node-version: [14]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Node
        run: |
          curl -sL https://deb.nodesource.com/setup_{{ matrix.node-version }}.x -o nodesource_setup.sh
          bash nodesource_setup.sh
          apt install nodejs  
      
      - uses: actions/checkout@v2
        with:
          submodules: recursive
        
      - name: install git if running locally
        if: ${{ env.ACT }}
        run: |
          apt-get update -y
          apt-get install git -y

      - name: Get bids-examples data
        run: git clone --depth 1 https://github.com/bids-standard/bids-examples -b ${{ matrix.bids-examples-branch }}

      - name: Try what the error code suggested
        run: git submodule update --init --depth 1

      - run: npm install
      
      - run: npm test
      
      #- name: Install git-annex ubuntu
      #  if: matrix.platform == 'ubuntu-latest'
      #  shell: bash -l {0}
      #  run: conda install -c conda-forge git-annex

      #- name: Install git-annex macos
      #  if: matrix.platform == 'macos-latest'
      #  shell: bash -l {0}
      #  run: brew install git-annex


      #- name: Install git-annex windows
      #  if: matrix.platform == 'windows-latest'
      #  uses: crazy-max/ghaction-chocolatey@v1
      #  with:
      #    args: install git-annex --yes --ignore-checksums
